#!/usr/bin/env sh

export REGION=${REGION-us-west1}
export ENVIRONMENT=${ENVIRONMENT-dev}
export TERRAFORM_DIRECTORY=${TERRAFORM_DIRECTORY-/terraform}
export SERVICE_NAME=${SERVICE_NAME-}

usage() {
  cat <<EOF
usage: $0 options

This script will perform the given terraform action after initializing the terraform state.
EOF
}

tf_init_with_local_backend() {
  terraform init \
    -get=true \
    "${TERRAFORM_DIRECTORY}"
}

tf_infrastructure() {
  echo "Running 'terraform $1 -var-file ${TERRAFORM_DIRECTORY}/${REGION}-${ENVIRONMENT}.tfvars ${TERRAFORM_DIRECTORY}'..."
  terraform $1 \
    -var-file "${TERRAFORM_DIRECTORY}/${REGION}-${ENVIRONMENT}.tfvars" \
    "${TERRAFORM_DIRECTORY}"
  echo "Completed terraform command."
}

tf() {
  echo "Running 'terraform $* ${TERRAFORM_DIRECTORY}'..."
  terraform \
    $* \
    "${TERRAFORM_DIRECTORY}"
  echo "Completed terraform command."
}

main() {
  tf_init_with_local_backend

  ACTION=${1}
  if [ "${ACTION}" = "plan" ] || [ "${ACTION}" = "apply" ] || [ "${ACTION}" = "destroy" ]; then
    tf_infrastructure "$*"
  else
    tf "$*"
  fi
}

check_variables() {
  if [ -z "${SERVICE_NAME}" ]; then
    echo "SERVICE_NAME must be provided."
    exit 1
  fi

  if [ $# -lt 1 ]; then
    usage
    exit 1
  fi
}

check_variables "$*"
main "$*"
