name: GCP Terraform Docker Release

on:
  release:
    types: [published]

jobs:
  lintMarkdown:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Markdown
      run: |
        make lint-markdown
  lintTerraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Terraform
      run: |
        make lint-terraform GITHUB_ACTION=true
  buildDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker
      run: |
        make build-docker
  performRelease:
    needs: [lintMarkdown, lintTerraform, buildDocker]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Perform Release
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
        run: |
          make release VERSION=$(echo $GITHUB_REF | cut -d '/' -f 3) GITHUB_USER=${{ github.actor }}
